#!/usr/bin/env python3
"""Regenerate event payload schema fixtures from events.rs.

Usage:
  python3 scripts/regen_event_payload_fixtures.py

Reads:
  contracts/bounty_escrow/contracts/escrow/src/events.rs
Writes:
  contracts/bounty_escrow/contracts/escrow/src/event_payload_fixtures.rs

After regenerating, run:
  cargo test -p bounty-escrow --lib event_payload_fixtures -- --nocapture
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVENTS = ROOT / "contracts/bounty_escrow/contracts/escrow/src/events.rs"
OUT = ROOT / "contracts/bounty_escrow/contracts/escrow/src/event_payload_fixtures.rs"


def clean_type(t: str) -> str:
    t = re.sub(r"//.*", "", t).strip().rstrip(",")
    return re.sub(r"\s+", " ", t)


def parse_structs(text: str):
    structs = []
    for m in re.finditer(r"pub struct (\w+)\s*\{", text):
        name = m.group(1)
        start = max(0, m.start() - 300)
        if "#[contracttype]" not in text[start : m.start()]:
            continue
        i = m.end()
        depth = 1
        while i < len(text) and depth:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        body = text[m.end() : i - 1]
        fields = []
        for line in body.splitlines():
            line = line.strip()
            if not line.startswith("pub "):
                continue
            line = line.split("//")[0].strip().rstrip(",")
            mm = re.match(r"pub\s+(\w+)\s*:\s*(.+)$", line)
            if mm:
                fields.append((mm.group(1), clean_type(mm.group(2))))
        structs.append((name, fields))
    return structs


def parse_enums(text: str):
    enums = []
    for m in re.finditer(r"pub enum (\w+)\s*\{", text):
        name = m.group(1)
        start = max(0, m.start() - 300)
        if "#[contracttype]" not in text[start : m.start()]:
            continue
        i = m.end()
        depth = 1
        while i < len(text) and depth:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        body = text[m.end() : i - 1]
        variants = []
        for line in body.splitlines():
            line = line.strip().rstrip(",")
            if not line or line.startswith("//") or line.startswith("#"):
                continue
            variants.append(line)
        enums.append((name, variants))
    return enums


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    if not EVENTS.is_file():
        print(f"missing {EVENTS}", file=sys.stderr)
        return 1
    text = EVENTS.read_text(encoding="utf-8")
    structs = parse_structs(text)
    enums = parse_enums(text)
    lines = []
    lines.append("//! Committed event payload schema fixtures for `events.rs`.")
    lines.append("//!")
    lines.append("//! These fixtures pin every emitted event's field declaration order and types.")
    lines.append("//! Reordering, renaming, adding, or removing a field fails the fixture check in")
    lines.append("//! `test_event_payload_fixtures.rs`.")
    lines.append("//!")
    lines.append("//! ## Versioning")
    lines.append("//!")
    lines.append("//! - Events with a `version: u32` field use [`crate::events::EVENT_VERSION_V2`].")
    lines.append("//! - **Breaking** payload changes (rename/remove/type change/reorder of existing")
    lines.append("//!   fields) must bump `EVENT_VERSION_V2`.")
    lines.append("//! - **Additive** changes (new optional fields) may keep the same version.")
    lines.append("//!")
    lines.append("//! ## Regenerating")
    lines.append("//!")
    lines.append("//! ```bash")
    lines.append("//! python3 scripts/regen_event_payload_fixtures.py")
    lines.append("//! ```")
    lines.append("//!")
    lines.append("//! @generated by scripts/regen_event_payload_fixtures.py — do not hand-edit.")
    lines.append("")
    lines.append("#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
    lines.append("pub struct FieldFixture {")
    lines.append("    pub name: &'static str,")
    lines.append("    pub ty: &'static str,")
    lines.append("}")
    lines.append("")
    lines.append("#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
    lines.append("pub struct EventPayloadFixture {")
    lines.append("    pub name: &'static str,")
    lines.append("    pub has_version_field: bool,")
    lines.append("    pub fields: &'static [FieldFixture],")
    lines.append("}")
    lines.append("")
    lines.append("#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
    lines.append("pub struct EnumFixture {")
    lines.append("    pub name: &'static str,")
    lines.append("    pub variants: &'static [&'static str],")
    lines.append("}")
    lines.append("")
    lines.append("/// Canonical event schema version pinned by fixtures (`EVENT_VERSION_V2`).")
    lines.append("pub const FIXTURE_EVENT_VERSION: u32 = 2;")
    lines.append("")
    lines.append("pub const EVENT_PAYLOAD_FIXTURES: &[EventPayloadFixture] = &[")
    for name, fields in structs:
        has_ver = any(n == "version" for n, _ in fields)
        lines.append("    EventPayloadFixture {")
        lines.append(f'        name: "{name}",')
        lines.append(f"        has_version_field: {'true' if has_ver else 'false'},")
        lines.append("        fields: &[")
        for fn, ft in fields:
            lines.append(f'            FieldFixture {{ name: "{esc(fn)}", ty: "{esc(ft)}" }},')
        lines.append("        ],")
        lines.append("    },")
    lines.append("];")
    lines.append("")
    lines.append("pub const EVENT_ENUM_FIXTURES: &[EnumFixture] = &[")
    for name, variants in enums:
        lines.append("    EnumFixture {")
        lines.append(f'        name: "{name}",')
        lines.append("        variants: &[")
        for v in variants:
            lines.append(f'            "{esc(v)}",')
        lines.append("        ],")
        lines.append("    },")
    lines.append("];")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(structs)} events, {len(enums)} enums)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
