//! Committed event payload schema fixtures for `events.rs`.
//!
//! These fixtures pin every emitted event's field declaration order and types.
//! Reordering, renaming, adding, or removing a field fails the fixture check in
//! `test_event_payload_fixtures.rs`.
//!
//! ## Versioning
//!
//! - Events with a `version: u32` field use [`crate::events::EVENT_VERSION_V2`].
//! - **Breaking** payload changes (rename/remove/type change/reorder of existing
//!   fields) must bump `EVENT_VERSION_V2`.
//! - **Additive** changes (new optional fields) may keep the same version.
//!
//! ## Regenerating
//!
//! ```bash
//! python3 scripts/regen_event_payload_fixtures.py
//! ```
//!
//! @generated by scripts/regen_event_payload_fixtures.py — do not hand-edit.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FieldFixture {
    pub name: &'static str,
    pub ty: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct EventPayloadFixture {
    pub name: &'static str,
    pub has_version_field: bool,
    pub fields: &'static [FieldFixture],
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct EnumFixture {
    pub name: &'static str,
    pub variants: &'static [&'static str],
}

/// Canonical event schema version pinned by fixtures (`EVENT_VERSION_V2`).
pub const FIXTURE_EVENT_VERSION: u32 = 2;

pub const EVENT_PAYLOAD_FIXTURES: &[EventPayloadFixture] = &[
    EventPayloadFixture {
        name: "BountyEscrowInitialized",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "token", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminRotationProposed",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "current_admin", ty: "Address" },
            FieldFixture { name: "pending_admin", ty: "Address" },
            FieldFixture { name: "timelock_duration", ty: "u64" },
            FieldFixture { name: "execute_after", ty: "u64" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminRotationAccepted",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "previous_admin", ty: "Address" },
            FieldFixture { name: "new_admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminRotationCancelled",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "cancelled_pending_admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminRotationTimelockUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "previous_duration", ty: "u64" },
            FieldFixture { name: "new_duration", ty: "u64" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "FundsLocked",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "depositor", ty: "Address" },
            FieldFixture { name: "deadline", ty: "u64" },
            FieldFixture { name: "correlation_id", ty: "Option<CorrelationId>" },
        ],
    },
    EventPayloadFixture {
        name: "FundsReleased",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "recipient", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
            FieldFixture { name: "correlation_id", ty: "Option<CorrelationId>" },
        ],
    },
    EventPayloadFixture {
        name: "EscrowPublished",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "published_by", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "FundsRefunded",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "refund_to", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
            FieldFixture { name: "trigger_type", ty: "RefundTriggerType" },
            FieldFixture { name: "correlation_id", ty: "Option<CorrelationId>" },
        ],
    },
    EventPayloadFixture {
        name: "RefundApprovalSet",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "recipient", ty: "Address" },
            FieldFixture { name: "mode", ty: "crate::RefundMode" },
            FieldFixture { name: "approved_by", ty: "Address" },
            FieldFixture { name: "approved_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "RefundApprovalConsumed",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "refunded_amount", ty: "i128" },
            FieldFixture { name: "refunded_to", ty: "Address" },
            FieldFixture { name: "consumed_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "OracleConfigUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "oracle_address", ty: "Address" },
            FieldFixture { name: "enabled", ty: "bool" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "FeeCollected",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "operation_type", ty: "FeeOperationType" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "fee_rate", ty: "i128" },
            FieldFixture { name: "fee_fixed", ty: "i128" },
            FieldFixture { name: "recipient", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "BatchFundsLocked",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "count", ty: "u32" },
            FieldFixture { name: "total_amount", ty: "i128" },
            FieldFixture { name: "timestamp", ty: "u64" },
            FieldFixture { name: "correlation_id", ty: "Option<CorrelationId>" },
        ],
    },
    EventPayloadFixture {
        name: "FeeConfigUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "lock_fee_rate", ty: "i128" },
            FieldFixture { name: "release_fee_rate", ty: "i128" },
            FieldFixture { name: "lock_fixed_fee", ty: "i128" },
            FieldFixture { name: "release_fixed_fee", ty: "i128" },
            FieldFixture { name: "fee_recipient", ty: "Address" },
            FieldFixture { name: "fee_enabled", ty: "bool" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "EscrowArchived",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "FeeRoutingUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "treasury_recipient", ty: "Address" },
            FieldFixture { name: "treasury_bps", ty: "i128" },
            FieldFixture { name: "partner_recipient", ty: "Option<Address>" },
            FieldFixture { name: "partner_bps", ty: "i128" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "FeeRoutingChanged",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "old_treasury_recipient", ty: "Option<Address>" },
            FieldFixture { name: "old_partner_recipient", ty: "Option<Address>" },
            FieldFixture { name: "new_treasury_recipient", ty: "Address" },
            FieldFixture { name: "new_partner_recipient", ty: "Option<Address>" },
            FieldFixture { name: "changed_by", ty: "Address" },
            FieldFixture { name: "post_lock_override", ty: "bool" },
            FieldFixture { name: "reason", ty: "Option<soroban_sdk::String>" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "FeeRouted",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "operation_type", ty: "FeeOperationType" },
            FieldFixture { name: "gross_amount", ty: "i128" },
            FieldFixture { name: "total_fee", ty: "i128" },
            FieldFixture { name: "fee_rate", ty: "i128" },
            FieldFixture { name: "treasury_recipient", ty: "Address" },
            FieldFixture { name: "treasury_fee", ty: "i128" },
            FieldFixture { name: "partner_recipient", ty: "Option<Address>" },
            FieldFixture { name: "partner_fee", ty: "i128" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "BatchFundsReleased",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "count", ty: "u32" },
            FieldFixture { name: "total_amount", ty: "i128" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "BatchSizeCapsUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "previous_lock_cap", ty: "u32" },
            FieldFixture { name: "new_lock_cap", ty: "u32" },
            FieldFixture { name: "previous_release_cap", ty: "u32" },
            FieldFixture { name: "new_release_cap", ty: "u32" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ApprovalAdded",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "contributor", ty: "Address" },
            FieldFixture { name: "approver", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ClaimCreated",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "recipient", ty: "Address" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "expires_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ClaimExecuted",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "recipient", ty: "Address" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "claimed_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ClaimCancelled",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "recipient", ty: "Address" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "cancelled_at", ty: "u64" },
            FieldFixture { name: "cancelled_by", ty: "Address" },
        ],
    },
    EventPayloadFixture {
        name: "DeterministicSelectionDerived",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "selected_index", ty: "u32" },
            FieldFixture { name: "candidate_count", ty: "u32" },
            FieldFixture { name: "selected_beneficiary", ty: "Address" },
            FieldFixture { name: "seed_hash", ty: "BytesN<32>" },
            FieldFixture { name: "winner_score", ty: "BytesN<32>" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "FundsLockedAnon",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "depositor_commitment", ty: "BytesN<32>" },
            FieldFixture { name: "deadline", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "DeprecationStateChanged",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "deprecated", ty: "bool" },
            FieldFixture { name: "migration_target", ty: "Option<Address>" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "MaintenanceModeChanged",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "enabled", ty: "bool" },
            FieldFixture { name: "reason", ty: "Option<soroban_sdk::String>" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "MaintenanceModeChangedV2",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "previous_enabled", ty: "bool" },
            FieldFixture { name: "enabled", ty: "bool" },
            FieldFixture { name: "reason", ty: "Option<soroban_sdk::String>" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ParticipantFilterModeChanged",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "previous_mode", ty: "crate::ParticipantFilterMode" },
            FieldFixture { name: "new_mode", ty: "crate::ParticipantFilterMode" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ParticipantFilterEntryUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "list_type", ty: "ParticipantFilterListType" },
            FieldFixture { name: "address", ty: "Address" },
            FieldFixture { name: "enabled", ty: "bool" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ParticipantFilterQueried",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "list_type", ty: "ParticipantFilterListType" },
            FieldFixture { name: "offset", ty: "u32" },
            FieldFixture { name: "limit", ty: "u32" },
            FieldFixture { name: "result_count", ty: "u32" },
            FieldFixture { name: "total", ty: "u32" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ParticipantListSchemaVersionSet",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "schema_version", ty: "u32" },
            FieldFixture { name: "set_by", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "RiskFlagsUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "previous_flags", ty: "u32" },
            FieldFixture { name: "new_flags", ty: "u32" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "MetadataUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "previous_repo_id", ty: "u64" },
            FieldFixture { name: "new_repo_id", ty: "u64" },
            FieldFixture { name: "previous_issue_id", ty: "u64" },
            FieldFixture { name: "new_issue_id", ty: "u64" },
            FieldFixture { name: "previous_bounty_type", ty: "soroban_sdk::String" },
            FieldFixture { name: "new_bounty_type", ty: "soroban_sdk::String" },
            FieldFixture { name: "previous_reference_hash", ty: "Option<soroban_sdk::Bytes>" },
            FieldFixture { name: "new_reference_hash", ty: "Option<soroban_sdk::Bytes>" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "NotificationPreferencesUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "previous_prefs", ty: "u32" },
            FieldFixture { name: "new_prefs", ty: "u32" },
            FieldFixture { name: "actor", ty: "Address" },
            FieldFixture { name: "created", ty: "bool" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "TicketIssued",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "ticket_id", ty: "u64" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "beneficiary", ty: "Address" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "expires_at", ty: "u64" },
            FieldFixture { name: "issued_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "TicketClaimed",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "ticket_id", ty: "u64" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "claimer", ty: "Address" },
            FieldFixture { name: "claimed_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "EmergencyWithdrawEvent",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "recipient", ty: "Address" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "CapabilityIssued",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "capability_id", ty: "BytesN<32>" },
            FieldFixture { name: "owner", ty: "Address" },
            FieldFixture { name: "holder", ty: "Address" },
            FieldFixture { name: "action", ty: "CapabilityAction" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "amount_limit", ty: "i128" },
            FieldFixture { name: "expires_at", ty: "u64" },
            FieldFixture { name: "max_uses", ty: "u32" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "CapabilityUsed",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "capability_id", ty: "BytesN<32>" },
            FieldFixture { name: "holder", ty: "Address" },
            FieldFixture { name: "action", ty: "CapabilityAction" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "amount_used", ty: "i128" },
            FieldFixture { name: "remaining_amount", ty: "i128" },
            FieldFixture { name: "remaining_uses", ty: "u32" },
            FieldFixture { name: "used_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "CapabilityRevoked",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "capability_id", ty: "BytesN<32>" },
            FieldFixture { name: "owner", ty: "Address" },
            FieldFixture { name: "revoked_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ExpiryConfigUpdated",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "default_expiry_duration", ty: "u64" },
            FieldFixture { name: "auto_cleanup_enabled", ty: "bool" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "EscrowExpired",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "creation_timestamp", ty: "u64" },
            FieldFixture { name: "expiry", ty: "u64" },
            FieldFixture { name: "remaining_amount", ty: "i128" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "EscrowCleanedUp",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "cleaned_by", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "GasBudgetCapExceeded",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "operation", ty: "Symbol" },
            FieldFixture { name: "cpu_used", ty: "u64" },
            FieldFixture { name: "mem_used", ty: "u64" },
            FieldFixture { name: "cpu_cap", ty: "u64" },
            FieldFixture { name: "mem_cap", ty: "u64" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "GasBudgetCapApproached",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "operation", ty: "Symbol" },
            FieldFixture { name: "cpu_used", ty: "u64" },
            FieldFixture { name: "mem_used", ty: "u64" },
            FieldFixture { name: "cpu_cap", ty: "u64" },
            FieldFixture { name: "mem_cap", ty: "u64" },
            FieldFixture { name: "threshold_bps", ty: "u32" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "GasBudgetAdvisoryNotice",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "caps_enforced_in_production", ty: "bool" },
            FieldFixture { name: "caps_configured", ty: "bool" },
            FieldFixture { name: "enforce_flag_set", ty: "bool" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "TimelockConfigured",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "delay", ty: "u64" },
            FieldFixture { name: "is_enabled", ty: "bool" },
            FieldFixture { name: "configured_by", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminActionProposed",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "action_type", ty: "CapabilityAction" },
            FieldFixture { name: "execute_after", ty: "u64" },
            FieldFixture { name: "proposed_by", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminActionExecuted",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "action_type", ty: "CapabilityAction" },
            FieldFixture { name: "executed_by", ty: "Address" },
            FieldFixture { name: "executed_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminActionCancelled",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "action_type", ty: "CapabilityAction" },
            FieldFixture { name: "cancelled_by", ty: "Address" },
            FieldFixture { name: "cancelled_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "RecurringLockCreated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "recurring_id", ty: "u64" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "depositor", ty: "Address" },
            FieldFixture { name: "amount_per_period", ty: "i128" },
            FieldFixture { name: "period", ty: "u64" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "RecurringLockExecuted",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "recurring_id", ty: "u64" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "amount_locked", ty: "i128" },
            FieldFixture { name: "cumulative_locked", ty: "i128" },
            FieldFixture { name: "execution_count", ty: "u32" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "RecurringLockCancelled",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "recurring_id", ty: "u64" },
            FieldFixture { name: "cancelled_by", ty: "Address" },
            FieldFixture { name: "cumulative_locked", ty: "i128" },
            FieldFixture { name: "execution_count", ty: "u32" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminTimelockConfigured",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "duration", ty: "u64" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminTransferProposed",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "old_admin", ty: "Address" },
            FieldFixture { name: "new_admin", ty: "Address" },
            FieldFixture { name: "available_at", ty: "u64" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminTransferCancelled",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "old_admin", ty: "Address" },
            FieldFixture { name: "proposed_admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "AdminTransferAccepted",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "old_admin", ty: "Address" },
            FieldFixture { name: "new_admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "MaxBatchSizeUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "old_size", ty: "u32" },
            FieldFixture { name: "new_size", ty: "u32" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ReentrancyAttemptBlocked",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "HighValueConfigUpdated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "threshold", ty: "i128" },
            FieldFixture { name: "duration", ty: "u64" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ReleaseQueued",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "contributor", ty: "Address" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "executable_at", ty: "u64" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "QueuedReleaseExecuted",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "contributor", ty: "Address" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "FeeRoutingInvariantChecked",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "operation_type", ty: "FeeOperationType" },
            FieldFixture { name: "gross_amount", ty: "i128" },
            FieldFixture { name: "fee_amount", ty: "i128" },
            FieldFixture { name: "distributed_total", ty: "i128" },
            FieldFixture { name: "weight_total", ty: "u64" },
            FieldFixture { name: "destination_count", ty: "u32" },
            FieldFixture { name: "invariant_ok", ty: "bool" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "FeeRoutingSchemaVersionSet",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "schema_version", ty: "u32" },
            FieldFixture { name: "set_by", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ReleaseQueueCancelled",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "contributor", ty: "Address" },
            FieldFixture { name: "amount", ty: "i128" },
            FieldFixture { name: "admin", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "HighValueConfigSchemaVersionSet",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "schema_version", ty: "u32" },
            FieldFixture { name: "set_by", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ClaimWindowSet",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "claim_window", ty: "u64" },
            FieldFixture { name: "set_by", ty: "Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ClaimWindowValidated",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "now", ty: "u64" },
            FieldFixture { name: "expires_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ClaimWindowExpired",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "bounty_id", ty: "u64" },
            FieldFixture { name: "now", ty: "u64" },
            FieldFixture { name: "expires_at", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "MaintenanceModeSchemaVersionSet",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "schema_version", ty: "u32" },
            FieldFixture { name: "set_by", ty: "soroban_sdk::Address" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ReentrancyGuardAcquired",
        has_version_field: true,
        fields: &[
            FieldFixture { name: "version", ty: "u32" },
            FieldFixture { name: "function", ty: "soroban_sdk::Symbol" },
            FieldFixture { name: "timestamp", ty: "u64" },
        ],
    },
    EventPayloadFixture {
        name: "ReleasedWithConversion",
        has_version_field: false,
        fields: &[
            FieldFixture { name: "escrow_id", ty: "u64" },
            FieldFixture { name: "src_asset", ty: "soroban_sdk::Address" },
            FieldFixture { name: "dest_asset", ty: "soroban_sdk::Address" },
            FieldFixture { name: "rate", ty: "i128" },
        ],
    },
];

pub const EVENT_ENUM_FIXTURES: &[EnumFixture] = &[
    EnumFixture {
        name: "RefundTriggerType",
        variants: &[
            "AdminApproval",
            "DeadlineExpired",
            "OracleAttestation",
        ],
    },
    EnumFixture {
        name: "FeeOperationType",
        variants: &[
            "Lock",
            "Release",
        ],
    },
    EnumFixture {
        name: "CriticalOperationOutcome",
        variants: &[
            "Released",
            "Refunded",
        ],
    },
    EnumFixture {
        name: "ParticipantFilterListType",
        variants: &[
            "Allowlist",
            "Blocklist",
        ],
    },
];

